name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      sdk-changed: ${{ steps.changes.outputs.sdk }}
      langchain-changed: ${{ steps.changes.outputs.langchain }}
      react-changed: ${{ steps.changes.outputs.react }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            sdk:
              - 'packages/sdk/**'
            langchain:
              - 'packages/langchain/**'
            react:
              - 'packages/react/**'

  publish-sdk:
    needs: detect-changes
    if: needs.detect-changes.outputs.sdk-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build SDK
        run: |
          cd packages/sdk
          pnpm run build

      - name: Publish SDK
        run: |
          cd packages/sdk
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-langchain:
    needs: [detect-changes, publish-sdk]
    if: needs.detect-changes.outputs.langchain-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Langchain
        run: |
          cd packages/langchain
          pnpm run build

      - name: Publish Langchain
        run: |
          cd packages/langchain
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-react:
    needs: [detect-changes, publish-sdk]
    if: needs.detect-changes.outputs.react-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build React
        run: |
          cd packages/react
          pnpm run build

      - name: Publish React
        run: |
          cd packages/react
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
