name: Release & Publish

on:
  push:
    branches:
      - main
    paths:
      - "packages/sdk/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: pnpm install
        working-directory: packages/sdk
      - run: pnpm release
        working-directory: packages/sdk
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
      - run: git push --follow-tags
        working-directory: packages/sdk
      - run: pnpm build
        working-directory: packages/sdk
      - run: pnpm publish --access public
        working-directory: packages/sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
